### ISSUE TITLE
GCN의 단점을 말해보자

### ISSUE THREAD

**Issue by ZiminPark** [RS-KR/GNN-RS-Beginner#15]
![image](https://user-images.githubusercontent.com/48933016/147992529-206cc21c-5e1b-40d0-8bbb-d4df37df059b.png)

**Comment by ZiminPark** [comment]
`GCN과 GraphSage의 차이점을 말해보라` 라고 하면 어떻게 대답?

**Comment by ZiminPark** [comment]
https://distill.pub/2021/understanding-gnns/#interactive

**Comment by choco9966** [comment]
- 문제1. 전체 Graph 구조를 알고 있을때 사용할 수 있는 방법. Spectral-based 모델은 푸리에 변환에 기반하여 그래프를 다룸. 따라서 새로운 노드가 추가되는 등, 그래프가 바뀌는 경우는 아예 고유벡터부터 새로 계산해야 해서 모델을 다시 학습해야 한다. 즉 그래프가 고정되어있는 형태에 대해서만 다룰 수 있음 
- 해결 : Spectral 처럼 모든 Graph를 사용하는게 아니라, 주변 노드의 정보만 활용하도록 Spatial한 모델을 사용 

- 문제2. 업데이트시에 한번에 업데이트 해야하지만, 메모리 공간 상에서 Full Batch로 한번에 올릴 수 없기에 Mini-Batch로 올림. 하지만, Dense Network의 경우 배치마다 Full Network와 유사한 복잡도가 형성 (2-hop의 노드 수 만으로 전체 노드와 비슷해질 수가 있음) 
- 해결 : 전체 연결된 노드를 다 사용하지 말고, 샘플링 하자 

출처 : https://thejb.ai/comprehensive-gnns-4/ , https://www.youtube.com/watch?v=y52qSiGOhbs&list=PLHzEkc0RJOwAvEbyTwgnPqoks8t2PrLmz&index=3

**Comment by ZiminPark** [comment]
GraphSage대신 GCN의 장점도 있을까?
> 데이터가 작으면 샘플링을 안하고 전체를 보는게 좋을수도

또다른 단점
> mini-batch를 못쓴다

**Comment by ZiminPark** [comment]
GCN이 Mini-Batch가 가능한가?

**Comment by choco9966** [comment]
오늘 GCN 관련 특강을 들을 기회가 있어서 위의 얘기에 대해서 물어봤습니다. 저도 완벽히 이해한건 아닌데 정리해보면, 

문제1. 전체 Graph 구조를 알고 있을때 사용할 수 있는 방법. Spectral-based 모델은 푸리에 변환에 기반하여 그래프를 다룸. 따라서 새로운 노드가 추가되는 등, 그래프가 바뀌는 경우는 아예 고유벡터부터 새로 계산해야 해서 모델을 다시 학습해야 한다. 즉 그래프가 고정되어있는 형태에 대해서만 다룰 수 있음

해결 : Spectral 처럼 모든 Graph를 사용하는게 아니라, 주변 노드의 정보만 활용하도록 Spatial한 모델을 사용

(수정) 여기에서, **고유벡터부터 새로 계산** 하는 부분은 GCN 연산중에  𝑘-th order polynomials of Laplacians 으로 approximation 하는 부분때문에 필요가 없는 것 같습니다. 대신, 새로운 노드가 들어오는 경우 Adjency matrix A와 Degree matrix D가 달라지기에 계산을 다시 해야할 필요성이 있는 것 같습니다. 

문제2. 업데이트시에 한번에 업데이트 해야하지만, 메모리 공간 상에서 Full Batch로 한번에 올릴 수 없기에 Mini-Batch로 올림. 하지만, Dense Network의 경우 배치마다 Full Network와 유사한 복잡도가 형성 (2-hop의 노드 수 만으로 전체 노드와 비슷해질 수가 있음)

해결 : 전체 연결된 노드를 다 사용하지 말고, 샘플링 하자

(수정) Full Batch와 Mini Batch 얘기부터 하자면, GCN에서도 Mini Batch는 가능하다고 얘기를 합니다. 단, 기준이 어떻게 되냐에 따라서 다릅니다. 노드를 기준으로 계산을 할 경우에 배치를 적용해도 A, D의 matrix의 크기는 변함이 없으니깐 메모리 관점에서 코스트는 동일하다고 합니다. 근데, 이를 엣지 관점에서 계산할 경우는 (1, 4), (2, 3), (4, 6) 이런식으로 노드간의 연결인 엣지 리스트로 표현하면 이에 대해 샘플링이 가능하다고 합니다. 

관련해서는 영수님도 같이 들어서 다음에 기깔나게 설명해주실 것 같습니다 ㅎㅎ
