### ISSUE TITLE
knowledge aware attention 이 무슨 의미일까?

### ISSUE THREAD

**Issue by haconedu** [RS-KR/GNN-RS-Beginner#26]

**Comment by ZiminPark** [comment]
![image](https://user-images.githubusercontent.com/48933016/150971872-18e1434b-cb34-4be8-9f1c-c9fc37e49c37.png)

**Comment by tdns03** [comment]
![image](https://user-images.githubusercontent.com/18159341/150974217-132bf9f6-305d-40fb-8199-eadc4169df38.png)
